// This file can be replaced during build by using the `fileReplacements` array.
// Both the `production` and `local` configurations replace `environment.ts`
// with `environment.local.ts` (generated by scripts/inject-env.mjs from real
// Supabase credentials). The list of file replacements can be found in
// `angular.json`.
//
// This file itself is only used by `ng test` and any configuration that
// omits a fileReplacement, so it stays a safe empty-string placeholder.
// SupabaseService fails soft (client=null) rather than throw when these are
// empty/invalid, and every Supabase-facing service (AuthService, NotesService,
// TutorsService, BookingsService, FavoritesService, MessagesService) follows
// that same convention.

export const environment = {
  production: false,
  supabaseUrl: '',
  supabaseAnonKey: '',
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
